---
sudo: false
language: ruby

env:
  global:
    - CC_TEST_REPORTER_ID=e91dbff92783b09f531028ccb33b372a03b8ee2ec0b15bf8e250359c80e06838

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

before_install: gem install bundler -v 2.0.2

cache:
  - bundler
  - apt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
